linters:
  enable:
    - gofmt          # Enforce standard Go formatting
    - gofumpt        # Stricter gofmt (extra formatting rules)
    - goimports      # Check import organization
    - govet          # Examine Go source code and report suspicious constructs
    - errcheck       # Check for unchecked errors
    - staticcheck    # Advanced static analysis
    - unused         # Check for unused code
    - gosimple       # Suggest code simplifications
    - ineffassign    # Detect ineffectual assignments
    - typecheck      # Standard Go type checker

linters-settings:
  gofmt:
    simplify: true   # Simplify code where possible

  gofumpt:
    extra-rules: true  # Enable extra formatting rules

  errcheck:
    check-blank: false  # Don't check blank assignments (allows _ = in defer closures)

  govet:
    enable-all: true
    disable:
      - shadow  # Disable shadow checking (common pattern in tests)

  staticcheck:
    checks: ["all"]

run:
  timeout: 5m
  tests: true
  go: "1.24"  # Match golangci-lint's build version to avoid version check failures

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
